services:
  - type: web
    name: constroiverse-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: MONGO_URI
        value: ${MONGO_URI}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}